---
- hosts: ansi_master
  sudo: yes
  gather_facts: False
  vars:
    filePath: '/tmp/daily_sync_scripts/dailyBackup.sh'
    bucketName: 'terascripts123'
    aws_access_key: 'xxxx'
    aws_secret_key: 'xxxx'
  
  tasks:
   - name: Create the folders if doesnot exists
     file: path=/tmp/daily_sync_scripts state=directory mode=0755
  
   - name: Downloading the script file from S3 bucket
     s3: aws_access_key={{ aws_access_key }} aws_secret_key={{ aws_secret_key }} bucket={{bucketName}} object=/Backup_scripts/Deploy.sh.txt dest={{filePath}} mode=get
   
   - name: Changing the execute permission for the deploy.sh file
     file: path={{ filePath }} mode=755

   - name: Adding the cron entry for executing the backup scripts
     cron: name="Cron entry for backupscript" special_time="daily" job="{{ filePath }} > /dev/null"
   
   - name: Checking pip is installed
     command: 'bash -c ls /usr/lib/python2.7/site-packages | grep -w "pip" | wc -l'
     register: pip_check

   - name: Installing Python PIP if not installed
     yum: name=python-pip state=present
     when: pip_check > 0
 
   - name: Chekcing BOTO module is installed
     command: bash -c "pip list | grep boto | wc -l"
     register: boto_install_check
     when: pip_check > 0

   - name: Checking AWS CLI if not installed
     command: bash -c 'pip list | grep awscli | wc -l'
     register: aws_install_check
     when: pip_check > 0
   
   - name: Installing boto module if not present
     pip: name=boto state=latest
     when: boto_install_check > 0

   - name: Installing AWS CLI if not present
     pip: name=awscli state=latest
     when: aws_install_check > 0

